name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: write

env:
  FILE_NAME_PREFIX: geoman-io-leaflet-geoman

jobs:
  build:
    environment: release
    name: release job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Important so we can merge branches
          fetch-depth: 0

      - name: Set version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Check version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "${{ steps.version.outputs.version }}" != "$PACKAGE_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/cache@v4
        name: Setup npm cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-store-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-store-

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Prepare package
        run: npm pack

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          token: ${{ secrets.GEOMAN_RELEASE_TOKEN }}
          files: |
            ${{env.FILE_NAME_PREFIX}}-${{ steps.version.outputs.version }}.tgz
            LICENSE

      - name: Publish to NPM
        run: npm publish --no-git-checks

      - name: Merge changes from develop into master
        # Only run when a tag triggers the workflow
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Get version
          PACKAGE_VERSION=$(node -p "require('./package.json').version")

          # Configure git
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Ensure we have the latest refs
          git fetch origin +refs/heads/develop:refs/remotes/origin/develop +refs/heads/master:refs/remotes/origin/master

          # Checkout master and merge develop
          git checkout master
          #git merge origin/develop --no-edit
          git merge origin/develop -m "Merge version ${{ steps.version.outputs.version }} from develop to master"

          # Push merged changes back to master
          git push origin master
